### ISSUE TITLE
Number of problem count doesn't get updated

### ISSUE THREAD

**Issue by flash7even** [forthright48/cpps#37]
After changing the parent folder of any folder the number of problem is not updating for the new parent folder. For example Centroid Decomposition folder was not included in Graph folder initially. But later i updated it to Graph folder. But the number of problem count of Graph folder still shows zero.

**Comment by forthright48** [comment]
Ok. This is a serious problem. If you relocate a folder, the ancestor list of THAT folder gets updated, but not the items inside that folder. Either I need to recursively update them, or find a better way. This might need some thinking.
